### ISSUE TITLE
Support `cloudformation package`

### ISSUE THREAD

**Issue by mkielar** [Kotaimen/awscfncli#11]
We're working with nested stacks a lot, effectively having 50+ template files. So far, we've been using `cloudformation package` with `--output-template-file` option, followed by `cloudformation update-stack` pointed to the local file generated by `package`.

The problem is that `cloudformation package` generates file names that look like `3492974862e431dc045af45c71555b17.template`, including the master template. This makes it really hard to point the `awscfncli` to such file. Instead I'd like to:
- either be able to package & deploy in one go with `awscfncli`
- or be able to point `awscfncli` with `TemplateURL` parameter to a file on local machine.

**Comment by Kotaimen** [comment]
You can enable `Packaging` in the configuration file and `awscfncli` will automatically package and upload to a pre-defined bucket `(awscfncli-${AWS_ACCOUNT_ID}-${AWS_REGION})`.

```yaml

Stack:
  TemplateBody:   ./foobar/foobar
  Region:         ap-southeast-1
  StackName:     foobar
  Capabilities:   [CAPABILITY_IAM]

  Package:        true
```

We have a 2.0 release on the way which is more suited to the "enterprise" environment, (eg: you can customize the upload bucket), stay tuned!
