### ISSUE TITLE
Support ordering when execute command on multiple stacks  

### ISSUE THREAD

**Issue by Kotaimen** [Kotaimen/awscfncli#26]
@GlieseRay Originally my plan is defer this feature to `2.1` and discover the stack dependency automatically.  However this  is a must have feature when deploy a set of related stacks in a single stage, otherwise the "stack select" option is less useful since you have to deploy separate stacks manually.

Now I opt for manually specify deployment order of stacks and stage in the configuration file, the order is decided by:

1. `DeployOrder` parameter of stage and stack,
2. Order of stage name and stack name.
 
For example:

```yaml
Stages:

  Foundation:
    DeployOrder: 1  
    VPC:

  Develop:
    DeployOrder: 2
      Database: 
        DeployOrder: 1
      Service: 
        DeployOrder: 2

  Production:
    DeployOrder: 3
      1_Database: 
         Parameter: Value
      2_Service: 
         Parameter: Value
```

Deployment order for the config is:

1. Foundation.VPC
2. Develop.Database
3. Develop.Service
4. Production.1_Database
5. Production.2_Service

**Comment by GlieseRay** [comment]
A global stack order is supported now. Stacks with same order number will be deployed in a random order. The following stacks will be deployed in the following order.

- Foundation.VPC
- Develop.Database
- Production.Database
- Develop.Service
- Production.Service
- Routing.DNS


```
Stages:
  Foundation:
    VPC:
      Order: 0  
  Develop:
    Database: 
      Order: 1
    Service: 
      Order: 2
  Production:
    Database: 
      Order: 1
    Service: 
      Order: 2
  Routing:
    DNS:
      Order: 3
```

**Comment by Kotaimen** [comment]
Stack order should be stage local, and stage is controlled by “stage order”.

A global order will impact how stage is effectively reused.

**Comment by GlieseRay** [comment]
Updated as following

```
Stages:
  Foundation:
    Order: 0
    VPC:
      Order: 0
  Develop:
    Order: 1
    Database:
      Order: 1
    Service:
      Order: 2
  Production:
    Order: 2
    Database:
      Order: 1
    Service:
      Order: 2
 ```

Order of deployment will be:

- Foundation.VPC
- Develop.Database
- Develop.Service
- Production.Database
- Production.Service
