### ISSUE TITLE
Parameter Override Issue

### ISSUE THREAD

**Issue by Kotaimen** [Kotaimen/awscfncli#31]
```yaml
Blueprints:
  Bob180:
    Foo: bar

Stages:
  Default:
    Bob190:
      Extends: Bob180
      Parameters:
        Bob: 190

    Bob200:
      Extends: Bob180
      Parameters:
        Bob: 200
```
Parameters will both be set to Bob190 in this configuration file.
Suspecting this has something to do with "extends" logic.
