### ISSUE TITLE
Proposal for Cross account output parameter reference

### ISSUE THREAD

**Issue by GlieseRay** [Kotaimen/awscfncli#32]
```yaml
Stages:

  Production:
    Order: 2
    DDBTable1:
      Order: 1
      Extends: DDB
      StackName: DynamoDbTable1
      Region: us-west-2
      Tags:
        Environment: staging
      Parameters:
        ReadCapacityUnits: 10
      Outputs:
        - OutputKeyInTheTemplateOfDDBTable1

    DDBTable2:
      Order: 2
      Extends: DDB2Idx
      StackName: DynamoDbTable1
      Region: us-east-1
      Tags:
        Environment: staging
      Parameters:
        ReadCapacityUnits: 10
        WriteCapacityUnits:
          !GetAtt Production.DDBTable1.Outputs.OutputKeyInTheTemplateOfDDBTable1
```

Use same syntax as AWS cloudformation.
Explicitly declare parameter output and reference
