### ISSUE TITLE
Reference Stack in Environment Configuration

### ISSUE THREAD

**Issue by GlieseRay** [Kotaimen/awscfncli#4]
Proposal:
```
Defaults:
    Vpc:
        Profile: default
Environments:
    staging:
        Vpc1:
            from: Vpc
        Vpc2:
            from: Vpc
```
