### ISSUE TITLE
Allow for customization of the S3 Bucket

### ISSUE THREAD

**Issue by mkielar** [Kotaimen/awscfncli#57]
In [#11](https://github.com/Kotaimen/awscfncli/issues/11), you mentioned that in 2.x it will be possible to customize the S3 bucket used by cloudformation package. Yet I cannot find the option to do so, and the code section responsible for the bucket name doesn't look promising either.

Can I please have a way of customizing the S3 bucket?
I'm currently on 0.5x using cloudformation package as a separate call, and then running `cfn` to get he log tail, and I'm starting migration to 2.x, but this is what is blocking me currently from fully migrating to `sync` command.

**Comment by Kotaimen** [comment]
Hi @mkielar:
Yes, this feature is already implemented in 2.0 and later, you can overwrite the bucket using `ArtifactStore` parameter:
```yaml
Stages:

  Develop:
    ApiBackend-Develop:
    Template: template.yaml
    Capabilities: [CAPABILITY_IAM]
    Package: true
    Region: us-east-1
    ArtifactStore: awscfncli-889515947644-custom-artifact-bucket
```

Note `awscfncli` won't create custom bucket automatically and the bucket must be in the same region with your stack.
