### ISSUE TITLE
Allow for blueprints inheritance and multiple inheritance

### ISSUE THREAD

**Issue by mkielar** [Kotaimen/awscfncli#58]
Would you consider allowing Blueprints to extend each other?
Would you consider allowing multiple inheritance of Blueprints?

That would create an multi-level inheritance model where one could have a `Common` blueprint with shared configuration, and then inherit from it to create blueprints that are dedicated, say to a specific region or environment. 

E.g. if I have ~20 DynamoDB tables, and want to have different capacity on different environments, I could either extend the `Common` blueprint by only overriding capacity parameters, or I could create a separate Blueprint (a _Mixin_, really) with just the configuration for DynamoDB Capacity, and then, use both to extend the stack.

**Comment by Kotaimen** [comment]
Hi @GlieseRay: 

I think he is asking for "OOP" version of Blueprints which is technically feasible. I wonder how much effort is needed to check the dependency graph...?

**Comment by Kotaimen** [comment]
Hi @mkielar:

I believe you can use YAMl tags to achieve similar effect:

```yaml
account01: &account01
  Profile: foo

capacity01: &capacity01
  ReadCapacity: 10

BluePrints:
  BluePrint1:
    Template: foobar.yaml
    Parameters:
      Foo: bar

Stages:
  Dev:
    Stack1:
     <<: *account01
     Extends: BluePrint1
     Parameters:
       <<: capacity01
```
