### ISSUE TITLE
Support lambda layers

### ISSUE THREAD

**Issue by Kotaimen** [Kotaimen/awscfncli#63]

**Comment by Kotaimen** [comment]
This feature probably require change from our side, need to verify.

**Comment by Kotaimen** [comment]
Confirmed using latest `awscli`:

```yaml
Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GeoLayer
      ContentUri: ./layer.zip
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'Available under the BSD license.'
```
