### ISSUE TITLE
Support string substitutions in other places than Parameters

### ISSUE THREAD

**Issue by alytle** [Kotaimen/awscfncli#76]
Being able to add variable substitution in other places than just Parameters which are imported would be valuable.

For example, I would love to be able to do something like this:

```
Variables:
    ProjectName: myproject

Stages:
  dev:
    DDBTable1:
      StackName: ${Variables.ProjectName}-dynamodb-${StageName}
```

And have my Stack Name come out as `myproject-dynamodb-dev`.

I'd be willing to work on this if you agreed it would be a useful feature.
