### ISSUE TITLE
YAML configure overwrite nested dictionary

### ISSUE THREAD

**Issue by Kotaimen** [Kotaimen/awscfncli#8]
Assume following YAML:
``` YAML
Blueprints:
  Foo: &Foo
    A: a
    B:
      C: c
Environments:
  Default:
    Bar:
      <<: *Foo
      B:
        D: d
```
Expected value for `Bar.B` is `{'C':'c', 'D':'d'}` but will get `{'D':'d'}` instead.
Seems YAML anchors not working as expected?
