### ISSUE TITLE
Deal with same StackName with different profile in the same stage.

### ISSUE THREAD

**Issue by GlieseRay** [Kotaimen/awscfncli#9]
Currently, stacks should have different name in the same stage. However, in some circumstance, stacks with different profile should be allowed to have same name. (eg. different regions, accounts).

To deal with these conditions, here are some proposals for the config schema:

1. Use list instead of dict

```yaml
Stages:
  Dev:
    - StackName: StackA
      Region: us-east-1
      Profile: bob
    - StackName: StackA
      Region: us-east-2
      Profile: ray
```
2. Use a name space:

```yaml
Stages:
  Dev:
    bob.us-east-1.StackA:
      Template: test.template.yaml
    ray.us-east-2.StackA:
      Template: test.template.yaml
```

Looks like solution 1 is more simple and straight forward.

**Comment by Kotaimen** [comment]
Allowing identical stack name in a stage will cause confusion when using glob in the CLI, eg:

    cfn-cli -s Dev.StackA stack deploy
 
This matches two stacks and I think its not a good behavior.

I'm purposing a third option:
- Keep the dictionary structure and require all stacks in a stage to have a unique name.
- Add a optional `StackName` parameter so user can override stack name (default is use stack name specified in the stage)
- Add some JSON validation requiring stack name align with CloudFormation stack naming requirement. 

I think this requires minimum amount of work.

FYI, CLI has the ability to overwrite profile and region settings:

    cfn-cli --profile=ray --region=ap-northeast-1 --stack=Dev.StackA stack deploy

**Comment by GlieseRay** [comment]
Requiring unique name in same stage seems not a big restriction on user. However I think overriding StackName on cli is an low priority feature for now. 
I will add some pattern check on StackName during schema validation.

And an optional  StackName property will be added in the stack config. If it exists, its value will be used as the stack name. For example,

```yaml
Stages:
  Dev:
    StackA1:
      StackName: StackA
      Region: us-east-1
      Profile: bob
    StackA2:
      StackName: StackA
      Region: us-east-2
      Profile: ray
```
